[package]
name = "sin_macros"
version = "0.0.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
sin_types = { path = "../sin_types", version = "0.0.2" }
syn = "2"
quote = "1"
proc-macro2 = "1"
