[package]
name = "sin_types"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
hashbrown = "0.14.0"
litrs = "0.4"
once_cell = "1.18"
parking_lot = "0.12.1"
symbol = "0.1.9"
