[package]
name = "sin_types"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
staticize = ">= 0.1.1"
interned = ">= 0.1.4"
litrs = "0.4"
regex = "1"
once_cell = "1"
