[package]
name = "sin_types"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interned = "0"
litrs = "0.4"
